apiVersion: 1

contactPoints:
  - orgId: 1
    name: Intellidog Webhook
    receivers:
      - uid: intellidog-webhook-01
        type: webhook
        settings:
          url: http://intellidog:8000/webhook/grafana
          httpMethod: POST
        disableResolveMessage: false
