apiVersion: 1

datasources:
  - name: Intellidog SQLite
    type: frser-sqlite-datasource
    access: proxy
    isDefault: true
    jsonData:
      path: /app/data/events.db
    version: 1
    editable: false
